version: '3.0'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: infinity_reads_api_gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes: 
      - .:/usr/infinity-reads/api_gateway/
      - ./node_modules:/usr/infinity-reads/api_gateway/node_modules

  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports: 
      - "3306:${MYSQL_PORT}"
    volumes: 
      - ./db_user/data:/var/lib/mysql
